kind: pipeline
name: default

steps:
- name: build
  image: python
  commands:
  - pip install -r requirements.txt
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: u_docker
    password: 
      from_secret: p_docker
    repo: luisredda/drone-harness-plugin-param
    auto_tag: true
