kind: pipeline

name: default
steps:
- name: build
  image: python
  commands:
  - pip install -r requirements.txt
- name: publish
  image: plugins/docker
  settings:
    username: diegokoala
    password: 
      from_secret: DockerHub
    repo: diegokoala/drone-harness-plugin
    auto_tag: true
